### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by JoshCPJ** [iliaamiri/selenium-on-Linux-setup-dependencies#2]
Hey, 
Trying to use this for the icbc bot, what ar ethe steps for using this server in windows? Been trying to find guides and there’s nothing
Sorry :(

**Comment by iliaamiri** [comment]
Hi,
No worries at all. :)
Are you using docker to run Selenium server on?

**Comment by JoshCPJ** [comment]
No I don’t have a docker

**Comment by JoshCPJ** [comment]
It’s just i was following the guide the link provided but I have no idea where to run the docker part

**Comment by iliaamiri** [comment]
Hi again, 
You don't have to use docker container for it. 

**EDITTED**: (You can run Selenium server locally)

Try using this one: https://github.com/iliaamiri/selenium-setup-dependencies/tree/v4-windows-firefox

So: 
1. Install the Java using the Setup.exe file under `/Java.SE.Runtime.Environment.v8.Update.181.x64_p30download.com`
2. Replace your Java path with the one in the START.bat file (the command is almost at the end of the file).
3. Open up a command-prompt (like CMD) and go to the repository's location (wherever you cloned this repo)
4. Double-click on the START.bat to run the selenium server.

Then in the ICBC bot source code, go to [`config-sample.js`](https://github.com/iliaamiri/a-web-bot-for-booking-the-closest-possible-appointment-on-ICBC-Driver-Licensing/blob/main/config-sample.js) and change the `seleniumServer` and `seleniumServerPort` to these:
```js
const seleniumServer = "localhost";
const seleniumServerPort = 4444;
```

ALSO, I think the current firefox webdriver is out-dated. So, you might have to replace the current `[geckodriver](https://github.com/iliaamiri/selenium-on-Linux-setup-dependencies/blob/main/geckodriver)` with the latest one

If things didn't work out, try replacing the `geckodriver` with the latest one (and update your firefox to the latest version). 
You can download the latest version for `geckodriver` here: https://github.com/mozilla/geckodriver/releases

**Comment by JoshCPJ** [comment]
hi thank you so much but 

what do you mean by java replacing the java path?
like what am i replacing the path is in program fes/java/jre.1.8.0_181/bin/java.exe 
that’s the only java that is there on my computer 
sorry for being slow😅

**Comment by iliaamiri** [comment]
Oh, 
I meant the java path. Because when you install java (or any other application), the application ends up being installed under a path. On Windows systems, that path usually starts from `C:\Program\` or something similar.

In order to find this path, simply navigate to your `C` drive, and try finding the `\java\bin\java.exe` under either `C\Program\` or `C\Program (x86)\`. 

After finding out where that .exe is, just copy paste the path by clicking the nav bar in windows (by navbar i mean:) 
![image](https://user-images.githubusercontent.com/37903573/173748274-4470e706-fa61-44ba-a786-1cbcb7025ef4.png)

After copying this part and replacing it with the: 
![image](https://user-images.githubusercontent.com/37903573/173748887-d162c9a3-0643-478b-bee8-49390f8d6684.png)

Just add the trailing `\java.exe` yourself 😁 

And, save the file. 

That's for that part. Let me know how it goes 👍

**Comment by iliaamiri** [comment]
Please tag me when you answered cause I might not get notified by just replying @j-cabans (at least i think tagging on github works as I expect)

**Comment by JoshCPJ** [comment]
Yeah everything works but :) 
@iliaamiri 

last question, changing the main.py to surrey seems like a problem with the 
![image](https://user-images.githubusercontent.com/75456088/173752885-7617fb5b-5f23-441e-adce-99a65238d028.jpg)
![image](https://user-images.githubusercontent.com/75456088/173752965-759a344e-61b6-4771-b1c6-bca0ae3df4d8.jpg)

**Comment by iliaamiri** [comment]
Oh, shoot.. 
Let me take a look. I'll let you know

**Comment by JoshCPJ** [comment]
Yeah, it seems like the bot pastes the city in which results in incorrect suggestions but if you type it normally it’ll show proper suggestions

**Comment by iliaamiri** [comment]
Yes,
try to type slowly yourself "Surr.." and stop wherever you saw the right suggested (Surrey, BC ...) and just tell the bot to type that only. Because the bot will try to select the suggested one, so you wanna guide it to see that.

I couldn't try this myself, otherwise I would've do it for you and let you know. But I cant book an appointment anymore 😅 sorry abt that

**Comment by iliaamiri** [comment]
Basically, you need to find the sweet spot where the suggestion appears by just that part of the city's phrase. It might be just "Surrey", "Surrey, ", "Surrey, B", and so on... (maybe even the whole thing works only)
I had the same problem with typing "North Vancouver, BC"

**Comment by JoshCPJ** [comment]
The bot wouldn’t have the same suggestions as to me typing it.

Me typing “surr” will have surrey, bc under

the bot typing surrey will still show those suggested places

south cambie, etc

**Comment by iliaamiri** [comment]
try pasting that segment yourself.

like, paste the "Surr" as if you are the bot. (don't type it)

**Comment by JoshCPJ** [comment]
nope nothing shows up

**Comment by iliaamiri** [comment]
Do you mind if I dm you somewhere else and try doing it myself with your account?

**Comment by JoshCPJ** [comment]
Yeah you got discord?

**Comment by iliaamiri** [comment]
yes, redbolder#7000
